### PR TITLE
Add support for multiple maps

### LINKED ISSUE #136: Multiple Map Support
Create maps with names and allow them to be accessed in Clever Ways™️

### PR DESCRIPTION
**Pull request by atoghill**
This PR introduces support for multiple maps per asset. This brings with it changes to a few commands as well as a script to migrate existing maps to the new format.

### Maps

The way in which maps are stored within the YAML has changed significantly. Instead of maps and thier metadata being under the `mutable` and `mutable['map']` keys they are stored in the following format:

```
mutable:
    maps:
        <map_name>:
            map_height:
            map_width:
            map_layout:
            map:
```
As a consequence of these changes it will be necessary to adjust [Flight Inventory Diagrams](https://github.com/alces-software/flight-inventory-diagrams) to support the concept of multiple maps as they are now accessed slightly differently than before.

### Commands

`edit-map [ASSET_SPEC]` -> `edit-map MAP_NAME [ASSET_SPEC]`
`list-map ASSET INDEX`    -> `list-map ASSET MAP_NAME INDEX`

Both `edit-map` and `list-map` have a new mandatory argument `MAP_NAME`. For the former this is the name of the map the user wishes to edit/create. Whereas for the latter it is used to indicate which map to search within.

### Scripts

The `migrate_data` script has been renamed to `migrate_schema` to better indicate it's purpose and make room for a central migration script with the original name.

The new `migrate_data` script handles both migrating the schema and any existing maps by utilising both the `migrate_schema` and `migrate_maps` scripts.

Any asset with an existing map will need to be migrated to allow for further editing/listing of the map via the CLI. Once the migration has been run it will place the existing map under the `maps` key with a map name of "migrated".

Ideally any future migration scripts should be added to this central migration script.

Resolves #136 when merged.

### CODE REVIEW

**Comment by atoghill** [comment]
Summary of discussion with @DavidMarchant regarding the above:

1. Both the templates within `Flight Inventory` itself and the `Diagrams` plugin were planned to be adjusted but it is good that this was spotted again anyway. The changes for the latter can be found [here](https://github.com/alces-software/flight-inventory-diagrams/pull/2). 

   Shortly after the latest version of `Flight Inventory` is released I will be creating `Overware` specific templates within that application.  

2. The intention behind the changes to migrations that I made were to keep the existing script from getting unmanageable further down the line. By using a central script with smaller files that house each specific migration it would hopefully keep the code easy to manage and work with.

   However David is correct that this method did ignore the existing conventions for updating the schema which is partially down to me not fully knowing how that process was meant to work. This is something that could be worth documenting.

   The changes we discussed and that I plan on making are:
   * Keeping a central migration script that checks the schema version of each asset
   * Migration files will be separately stored under a new `scripts/migrations` directory and named in the format of `schema_x` where x is the schema version the file intends to migrate an asset to
   * Each migration file will not support being called separately, at least initially
   * The migration script will run all necessary migrations for an asset to bring it to the schema version specified in `version.rb`
   * It will again be possible to run the script on a specific asset by passing an argument to it. Although this functionality isn't necessarily useful in practice it helps for testing.
   * The migration that I made to adjust existing maps will be changed to correctly adjust the schema version

**Comment by DavidMarchant** [comment]
:heart_eyes:

**Comment by DavidMarchant** [comment]
As far as documentation, there's this in the README, do you think that's sufficient?
https://github.com/openflighthpc/flight-inventory/blame/feature/multiple-map-support/README.md#L113-L122

**Comment by atoghill** [comment]
I'm clearly blind. That looks sufficient for what currently exists, I'll probably update it to reflect the proposed changes

**Comment by atoghill** [comment]
@DavidMarchant My next branch is currently based off of this and is almost ready to be pushed. If there are any additional changes you want made to this PR then let me know before tomorrow as I'd like to merge this before putting the next one up if possible.

**Comment by DavidMarchant** [comment]
Nope! With the changes we've discussed else where that are coming shortly this LGTM

**Pull request merged**
